[package]
name = "rust-activitypub"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
liquid = "0.26.0"
diesel = { version = "2.0.0", features = ["sqlite"] }
dotenvy = "0.15"
rocket = "0.5.0-rc.2"

# https://github.com/cobalt-org/liquid-rust


[dependencies.rocket_dyn_templates]
rocket_dyn_templates = "0.1.0-rc.2"
features = ["tera"]

[dependencies.rocket_db_pools]
rocket = "0.5.0-rc.2"
features = ["sqlx_sqlite"]
