[package]
name = "rust-activitypub"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


# rustup override set nightly

[dependencies]
# serde = { version = "1", features = ["derive"] }
liquid = "0.26.0" 
dotenvy = "0.15"
rocket = { version = "0.5.0-rc.2", features = ["json"] }
sqlx = { version = "~0.6.2", features = ["macros", "migrate", "sqlite", "runtime-tokio-rustls"] }


#[dependencies.sqlx]
#version = "0.6.0"
#default-features = false
#features = ["macros", "offline", "migrate", "runtime-tokio-rustls"]

# https://github.com/cobalt-org/liquid-rust


[dependencies.rocket_dyn_templates]
rocket_dyn_templates = "0.1.0-rc.2"
features = ["tera"]

#[dependencies.rocket_db_pools]
#rocket = "0.5.0-rc.2"
#features = ["sqlx_sqlite"]

