[package]
name = "rustypub"
version = "0.1.0"
edition = "2021"
default-run = "server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


# rustup override set nightly

[dependencies]
activitystreams = "0.7.0-alpha.21"
activitystreams-ext = "0.1.0-alpha.3"
native-tls = { version = "~0.2.11", features = ["vendored"] }
openssl = { version = "~0.10.42", features = ["vendored"] }
openssl-sys = "~0.9.78"
liquid = "0.26.0" 
dotenvy = "0.15"
rocket = { version = "0.5.0-rc.2", features = ["json", "secrets"] }
sqlx = { version = "~0.6.2", features = ["chrono", "macros", "migrate", "sqlite", "runtime-tokio-rustls"] }
serde = {version = "~1.0", features = ["derive"] }
rand = { version = "0.8.5" }
feed-rs = "1.2"
reqwest = { version = "0.11", features = ["json"] }
http-signature-normalization-reqwest = { version = "0.7.1", default-features = false, features = ["sha-2", "middleware"] }
#http-signature-normalization = "0.6.0"

# this is only here for the parser bin
tokio = "1.22.0"
webfinger = { version = "0.5.1", features = ["async", "async-trait"] }
async-trait = {version = "*"}
serde_json = "1.0.89"
anyhow = "1.0.66"
reqwest-middleware = "0.2.0"
httpdate = "1.0.2"
url = "2.3.1"
sha2 = "0.10.6"
base64 = "0.13.1"
chrono = { version = "0.4.23", features = ["serde"] }
reqwest-tracing = "0.4.0"


# chrono = "~0.4.23"
# thiserror = { version = "~1.0.37" }

#[dependencies.sqlx]
#version = "0.6.0"
#default-features = false
#features = ["macros", "offline", "migrate", "runtime-tokio-rustls"]

# https://github.com/cobalt-org/liquid-rust


[dependencies.rocket_dyn_templates]
rocket_dyn_templates = "0.1.0-rc.2"
features = ["tera"]

#[dependencies.rocket_db_pools]
#rocket = "0.5.0-rc.2"
#features = ["sqlx_sqlite"]



[dev-dependencies]
native-tls = { version = "~0.2.11", features = ["vendored"] }
openssl = { version = "~0.10.42", features = ["vendored"] }
openssl-sys = "~0.9.78"

[build-dependencies]
native-tls = { version = "~0.2.11", features = ["vendored"] }
openssl = { version = "~0.10.42", features = ["vendored"] }
openssl-sys = "~0.9.78"
