---
version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pubcrawl
    restart: on-failure
    working_dir: /app
    volumes:
      - ./data/:/app/data/
    environment:
      DATABASE_URL: sqlite:data/data.sqlite3
      DOMAIN_NAME: foo.com
  # mail:
  #   image: mailhog/mailhog:latest
  #   ports:
  #     - 8025:8025
  #     - 1025:1025
