---
version: '3.8'
services:
  db:
    restart: always
    image: postgres:14-alpine
    shm_size: 256mb
    networks:
      - internal_network
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pubcrawl
    restart: on-failure
    working_dir: /app
    env_file:
      .env
    depends_on:
      - db
    ports:
      - 8000:8000
    networks:
      - external_network
      - internal_network
networks:
  external_network:
  internal_network:
    internal: true