name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  POSTGRES_PASSWORD: postgres
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v3
    - name: Switch to nightly
      run: rustup override set nightly
      #rustup update && cargo update
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
